const AuthActionTypes = {
	AUTH_REGISTRATION_START: 'AUTH_REGISTRATION_START',
	AUTH_REGISTRATION_SUCCESS: 'AUTH_REGISTRATION_SUCCESS',
	AUTH_REGISTRATION_FAILURE: 'AUTH_REGISTRATION_FAILURE',
	AUTH_CLEAR_GRAY_OUT: 'AUTH_CLEAR_GRAY_OUT'
}

export default AuthActionTypes 
